---
title: "Résumé"
author: "Taehee Lee"
date: "2/13/2022"
output: 
  stevetemplates::resume:
    dev: cairo_pdf
fontawesome: TRUE
# How can we get a hold of you?
email: tl592@cornell.edu
phone: 805-300-8160
location: "Ithaca, NY/Lawrenceville, NJ"
#github: 133taehee
#web: wwe.com/superstars/rick-martel
#twitter: "@rickmartelWWE"
linkedin: "taehlee"
geometry: "top=.5in, left =.5in, right=.5in, bottom=.75in"
mainfont: cochineal
sansfont: Fira Sans
# monofont: Fira Code # I want to use this, but seems to choke on @
urlcolor: blue
fontsize: 11pt

includephoto: FALSE
myphoto: headshot.jpg
# shift: "7in,-.25in" # this is default
photobigness: 1.75cm
# photozoom: ".2\textwidth" # this is default
---


<!-- Read more about Pandoc's [fenced_divs](https://pandoc.org/MANUAL.html#extension-fenced_divs) syntax -->

:::::: {.columns}
::: {.column width="60%" data-latex="{0.60\textwidth}"}

# Professional Experience

## R&D Engineer | Medtronic Diabetes, Northridge CA

- Collaborated in cross-functional engineering groups to ensure developing product designs met product requirements, regulatory guidelines, and international standards
-	Defined design requirements, specifications, and test methodologies for product in development
-	Analyzed and verified product designs and validated product manufacturing processes
-	Guided team members on verification, validation, and qualification activities for product development
-	Designed, set up, and executed experiments to evaluate design concepts
-	Communicated with FDA representatives to improve validation protocols and documentation
-	Managed process characterizations and validations in accordance with medical regulatory guidelines
-	Performed and reported process validations and part qualifications for products in production and in development


## Research Technician | Children's Hospital of Philadelphia, Philadelphia PA

*A zebrafish model of Friedreich ataxia for drug screening*

-	Lead investigator - Developed and validated CRISPR-Cas9 modified zebrafish through verification of mutant genotypes, evaluation of disease-associated phenotypes and face validity
-	Relevant techniques: antibody validation, SDS-PAGE, Western blot, qPCR, TIDE (Tracking of Indels by DEcomposition)

*Screening of random shRNA-expressing library in a cellular model of MELAS (Mitochondrial Encephalopathy, Lactic Acidosis, and Stroke-like episodes)*

-	Lead investigator - Identified reproducible conditions for in vitro screening, screened shRNA library and cloned candidates, investigated potentially affected pathways in MELAS
-	Relevant techniques: gene cloning, Seahorse metabolic assay, Oroboros respirometry assay, enzymatic assays, ELISA, flow cytometry






:::
::: {.column width="2%" data-latex="{0.02\textwidth}"}
\ 
<!-- an empty div with an empty character to serve as a column sep -->
:::
:::::: {.column width="38%" data-latex="{0.38\textwidth}"}

# Education

To continue the theme of this résumé, pro wrestlers of the time were typically not the kind that had university degrees, but you can insert your own here.

## Postgraduate Program

Ph.D. in Boston Crab Studies
 
## Undergraduate Program

B.A. in something or other.

# Technical Skills (or Accomplishments)

Put your technical skills here, or, if you're Rick Martel, list your pro-wrestling accolades.

## Championships

- AWA World Heavyweight Championship (1984)
- WCW World Television Championship (1998)
- NWA Pacific Northwest Heavyweight Championship (1980)
- NWA Pacific International Championship (1978)
- WWF Tag Team Championship (2x with Tony Garea, 1x with dead-weight Tito Santana)
- NWA Pacific Northwest Tag Team Championship (3x, with Roddy Piper in 1980)
- WWC North American Tag Team Championship (with Pierre Martel)

## Awards and Distinctions

- Pro Wrestling Hall of Fame (Class of 2015)
- New England Pro Wrestling Hall of Fame (Class of 2011)
- Ranked #48 of the 500 best singles wrestlers ("PWI Years", 2003)
- Ranked #70 (with dead-weight Tito Santana) of the 100 best tag teams ("PWI Years", 2003)
- World's Strongest Tag Determination League Fighting Spirit Award (1986)

:::
::::::

<!-- If you want another page, this is how you can do it... -->

<!-- \newpage

:::::: {.columns}
::: {.column width="60%" data-latex="{0.60\textwidth}"}




:::
::: {.column width="2%" data-latex="{0.02\textwidth}"}
\


:::
:::::: {.column width="38%" data-latex="{0.38\textwidth}"}


:::
::::::

-->
